Support hostnameIPv4 and hostnameIPv6
database64128/ddns-cloudflare-powershell pull request #1
Opened 2021-09-03 05:10 UTC by LinEvil

2021-09-03 05:12 UTC, LinEvil commented
- Support hostnameIPv4 and hostnameIPv6 
- Add EnableCompare
- Rename settings.jsonc to ~.example
- Send request to cloudflare without proxy

2021-09-03 05:28 UTC, database64128 commented
Can you make the use of proxy configurable too? In my use case, it's better to send the Cloudflare API request via proxy.

2021-09-03 05:47 UTC, LinEvil commented
According to [MSFT docs](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7.1#notes)
The request `Invoke-WebRequest` uses the proxy settings in the system environment variables by default.

Maybe an option to toggle it is helpful, I will do it later.

2021-09-03 06:16 UTC, database64128 commented
> Maybe an option to toggle it is helpful

That's what I meant. 😄

2021-09-03 16:59 UTC, database64128 requested changes

2021-09-03 16:59 UTC, database64128 commented on settings.jsonc.example
> +    "EnableCompare": true,
`Enable` -> `Enabled`

2021-09-03 16:59 UTC, database64128 commented on .gitignore
> +*.log
I prefer to have a new line at the end of a file.

2021-09-03 16:59 UTC, database64128 commented on settings.jsonc.example
> +    // The interval for periodic checks in seconds, 0 for an one-shot run.
an -> a

2021-09-04 05:23 UTC, database64128 commented on settings.jsonc.example
> +    "EnableCompare": true,
Sorry, GitHub seems to have messed up the position. `EnableCompare` is fine. My comment was targeting `IPv4.Enable` and `IPv6.Enable`.

2021-09-04 07:13 UTC, merged

2021-09-04 07:13 UTC, database64128 commented
Thank you for your work!